#!/bin/bash

cd vim

./configure --with-features=huge \
            --enable-multibyte \
            --enable-rubyinterp=dynamic \
            --enable-luainterp \
            --with-x=yes \
            --with-compiledby=alpardal@gmail.com \
            --enable-pythoninterp=yes \
            --with-python-config-dir=/usr/lib/python2.7/config-x86_64-linux-gnu \
            --enable-python3interp=yes \
            --with-python3-config-dir=/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu
