#!/bin/bash

cd vim

./configure --with-features=huge \
            --enable-multibyte \
            --enable-rubyinterp=dynamic \
            --enable-pythoninterp \
            --enable-luainterp \
            --with-x=yes \
            --with-compiledby=alpardal@gmail.com
