#!/bin/bash

cd vim

./configure --with-features=huge \
            --enable-multibyte \
            --enable-rubyinterp=dynamic \
            --enable-pythoninterp=yes \
            --enable-luainterp \
            --with-x=yes \
            --with-compiledby=alpardal@gmail.com \
            --with-python-config-dir=/usr/lib/python2.7/config-x86_64-linux-gnu
