MY_ZSHRC=`readlink ~/.zshrc`
DOTFILES_DIR=`dirname "$MY_ZSHRC"`/..

ZSH=$HOME/.oh-my-zsh
# ZSH_THEME="gallois"
# ZSH_THEME="bullet-train"
ZSH_THEME="zeta"

# plugins=(git colored-man-pages autojump)
plugins=(colored-man-pages)
source $ZSH/oh-my-zsh.sh

source $DOTFILES_DIR/shell/env.sh
source $DOTFILES_DIR/shell/aliases.sh
unalias md
source $DOTFILES_DIR/shell/functions.sh

if [[ -r "$HOME/.zshrc.local" ]]; then
    source $HOME/.zshrc.local
fi

fancy-ctrl-z () {
  if [[ $#BUFFER -eq 0 ]]; then
    BUFFER="fg"
    zle accept-line
  else
    zle push-input
    zle clear-screen
  fi
}
zle -N fancy-ctrl-z
bindkey '^Z' fancy-ctrl-z

setopt HIST_IGNORE_DUPS
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_SPACE
setopt HIST_FIND_NO_DUPS
setopt NUMERIC_GLOB_SORT

export PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh


# disable since it's causing issues when running tests
# export MIX_OS_DEPS_COMPILE_PARTITION_COUNT=$(nproc | sed 's/$/\/2/' | bc)
export MIX_OS_DEPS_COMPILE_PARTITION_COUNT=1

fpath=(${ASDF_DIR}/completions $fpath)

autoload -Uz compinit && compinit

eval "$(zoxide init zsh)"
